stages:
  - test
  - build

run_tests:
  stage: test
  script:
    - AT_WTIOIT_PYCHARM_PLUGIN_testVersion=$VERSION AT_WTIOIT_PYCHARM_PLUGIN_testType=$TYPE ./gradlew test
  after_script:
    - java -version
  parallel:
    matrix:
      - TYPE: "PC" # PyCharm Community
        VERSION: ["2019.2", "2019.3", "2020.1", "2020.2", "2020.3", "2021.1", "2021.2" ]
      - TYPE: "PY" # PyCharm Professional
        VERSION: [ "2019.2", "2019.3", "2020.1", "2020.2", "2020.3", "2021.1", "2021.2" ]
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports
    when: always

build:
  stage: build
  script:
    - ./gradlew buildPlugin
  artifacts:
    paths:
      - build/libs/odoo_plugin-*.jar